#!/bin/bash

user_menu() {
    while true; do
        PS3="Select an option for User: "
        select user_choice in "Add" "Delete" "Modify user ID" "Change password" "Back"
        do
            case $user_choice in
                "Add")
                    echo "Enter username to add:"
                    read username
                    sudo useradd $username
                    echo "User $username added."
                    break
                    ;;
                "Delete")
                    echo "Enter username to delete:"
                    read username
                    sudo userdel $username
                    echo "User $username deleted."
                    break
                    ;;
                "Modify user ID")
                    echo "Enter username whose ID you want to change:"
                    read username
                    echo "Enter new UID for $username:"
                    read new_uid
                    sudo usermod -u $new_uid $username
                    echo "User ID for $username changed to $new_uid."
                    break
                    ;;
                "Change password")
                    echo "Enter username to change password:"
                    read username
                    sudo passwd $username
                    echo "Password changed for $username."
                    break
                    ;;
                "Back")
                    return 
                    ;;
                *)
                    echo "Invalid option. Please try again."
                    ;;
            esac
        done
    done
}

group_menu() {
    while true; do
        PS3="Select an option for Group: "
        select group_choice in "Add group" "Modify group name" "Back"
        do
            case $group_choice in
                "Add group")
                    echo "Enter group name to add:"
                    read groupname
                    sudo groupadd $groupname
                    echo "Group $groupname added."
                    break
                    ;;
                "Modify group name")
                    echo "Enter old group name:"
                    read old_group
                    echo "Enter new group name:"
                    read new_group
                    sudo groupmod -n $new_group $old_group
                    echo "Group name changed from $old_group to $new_group."
                    break
                    ;;
                "Back")
                    return
                    ;;
                *)
                    echo "Invalid option. Please try again."
                    ;;
            esac
        done
    done
}

# Main menu loop
while true; do
    PS3="Select an option from the main menu: "
    select main_choice in "User" "Group" "Exit"
    do
        case $main_choice in
            "User")
                user_menu 
                break
                ;;
            "Group")
                group_menu
                break 
                ;;
            "Exit")
                echo "Exiting."
                exit 0 
                ;;
            *)
                echo "Invalid option. Please try again."
                ;;
        esac
    done
done

